name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean install
    
    - name: Run Tests
      run: ./mvnw test
    
    - name: Build Docker image
      run: docker build -t smart-home:${{ github.sha }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push Docker image
      run: |
        docker tag smart-home:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/smart-home:${{ github.sha }}
        docker tag smart-home:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/smart-home:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/smart-home:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/smart-home:latest
    
    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main'
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/deployment.yaml
        images: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/smart-home:${{ github.sha }} 